ARG VERSION
FROM almalinux:9
ARG COURSE="Devops" \
    Trainer="Siva kumar" \
    Trainee="Wasim"
ENV COURSE=${COURSE}
RUN echo "Trainer : ${Trainer} , Trainee : ${Trainee} , COURSE : ${COURSE}, VERSION : ${VERSION}"
CMD ["sleep", "1000"]